In [2]:
student_name = "Ram"
roll_no = 15
marks_math = 9.5

9.5

In [4]:
# single line comment

#= can contain multiline comment =#


#= This is an example to demonstrate the multi-line comments that tells us about tutorialspoint.com. 
At this website you can browse the best resource for Online Education.=#

In [5]:
#= An Array is an ordered set of elements which are often specified with squared brackets having comma-separated 
items. We can create arrays that are − 
1. Full or empty
2. Hold various types of data
3. Restricted to values of specific type =#

In [6]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [7]:
arr = [1,2,3, 'a', 'b']

5-element Array{Any,1}:
 1
 2
 3
  'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
  'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)

In [8]:
array = Array{Int64}(undef, 3)

3-element Array{Int64,1}:
 139827854857840
 139827852652896
 139827852652896

In [9]:
array = Array{Int64}(undef, 3, 3, 3)

3×3×3 Array{Int64,3}:
[:, :, 1] =
  8  139827773672128  139827808898912
  3  139827768466896  139827802217184
 32  139827783722544                1

[:, :, 2] =
 139827235989392                3  139827796031216
               1  139827793547024  139827796031152
              -1  139827793546928                2

[:, :, 3] =
               1                0  139827783722864
 139827854094656  139827793547120  139827775807520
 139827793547216  139827783722784  139826972131329

In [10]:
A = Int64[]

Int64[]

In [11]:
A = String[]

String[]

In [12]:
[1 2 3 4 5 6 7 8 9 10]

1×10 Array{Int64,2}:
 1  2  3  4  5  6  7  8  9  10

In [15]:
[1 2 3 4 5 ; 6 7 8 9 10;]

2×5 Array{Int64,2}:
 1  2  3  4   5
 6  7  8  9  10

#### Collect() function

First useful function to create an array using range objects is collect(). With the help of colon(:) and collect() function, we can create an array using range objects as follows

start:step:stop

In [16]:
collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [22]:
collect(:12)

0-dimensional Array{Int64,0}:
12

In [23]:
collect(1.5:5.5)

5-element Array{Float64,1}:
 1.5
 2.5
 3.5
 4.5
 5.5

#### ellipsis(…) or splat operator

Instead of using collect() function, we can also use splat operator or ellipsis(…) after the last element.

In [24]:
[0:10...]

11-element Array{Int64,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

#### range() function

Range() is another useful function to create an array with range objects. It goes from start value to end value by taking a specific step value.

In [25]:
range(1, length=15, stop=150)

1.0:10.642857142857142:150.0

In [26]:
range(1, stop=150, step=10)

1:10:141

In [27]:
collect(range(1, length=15, stop=150))

15-element Array{Float64,1}:
   1.0
  11.642857142857142
  22.285714285714285
  32.92857142857143
  43.57142857142857
  54.214285714285715
  64.85714285714286
  75.5
  86.14285714285714
  96.78571428571429
 107.42857142857143
 118.07142857142857
 128.71428571428572
 139.35714285714286
 150.0

Another useful way to create an array is to use comprehensions. In this way, we can create array where each element can produce using a small computation. For example, we can create an array of 10 elements as follows 

In [28]:
[n^2 for n in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [29]:
[n*m for n in 1:10, m in 1:10]

10×10 Array{Int64,2}:
  1   2   3   4   5   6   7   8   9   10
  2   4   6   8  10  12  14  16  18   20
  3   6   9  12  15  18  21  24  27   30
  4   8  12  16  20  24  28  32  36   40
  5  10  15  20  25  30  35  40  45   50
  6  12  18  24  30  36  42  48  54   60
  7  14  21  28  35  42  49  56  63   70
  8  16  24  32  40  48  56  64  72   80
  9  18  27  36  45  54  63  72  81   90
 10  20  30  40  50  60  70  80  90  100

In [30]:
collect(n^2 for n in 1:5)

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

### Populating an Array

Following are the functions with the help of which you can create and fill arrays with specific contents −
#### zeros (m, n)

This function will create matrix of zeros with m number of rows and n number of columns. The example is given below

In [31]:
zeros(4,5)

4×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [32]:
zeros(Int64,4,5)

4×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

#### ones (m, n)

This function will create matrix of ones with m number of rows and n number of columns. The example is given below

In [33]:
ones(4,5)

4×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

### rand (m, n)

As the name suggests, this function will create matrix of random numbers with m number of rows and n number of columns.

In [36]:
rand(4,5)

4×5 Array{Float64,2}:
 0.829394  0.261408   0.301023  0.986204  0.0465898
 0.177829  0.191439   0.707557  0.50394   0.249452
 0.345841  0.574306   0.100953  0.50094   0.368992
 0.995164  0.0407851  0.431756  0.95588   0.555763

#### randn(m, n)

As the name suggests, this function will create m*n matrix of normally distributed random numbers with mean=0 and standard deviation(SD)=1.

In [37]:
randn(4,5)

4×5 Array{Float64,2}:
  0.658813   -0.755717  -1.43305    0.362785  -1.744
 -2.49828     0.758181  -0.249511  -1.24204    1.27779
  1.00274    -0.210198   2.15374    0.540173   0.652497
  0.0225745  -0.462252  -0.577431  -1.82036   -0.234275

#### fill()

This function is used to fill an array with a specific value. More specifically, it will create an array of repeating duplicate value.

In [38]:
fill(100,5)

5-element Array{Int64,1}:
 100
 100
 100
 100
 100

#### fill!()

It is similar to fill() function but the sign of exclamation (!) is an indication or warning that the content of an existing array is going to be changed. The example is given below:

In [39]:
ABC = ones(5)

5-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [40]:
fill!(ABC,100)

5-element Array{Float64,1}:
 100.0
 100.0
 100.0
 100.0
 100.0

In [41]:
ABC

5-element Array{Float64,1}:
 100.0
 100.0
 100.0
 100.0
 100.0

### Array Constructor

The function Array(), we have studied earlier, can build array of a specific type as follows −

In [42]:
Array{Int64}(undef, 5)

5-element Array{Int64,1}:
 139827228905136
 139827228905232
 139827228905280
 139827228905328
 139827228905376

#### Arrays of arrays

In [43]:
ABC = Array[[3,4],[5,6]]

2-element Array{Array,1}:
 [3, 4]
 [5, 6]

In [44]:
Array[1:5,6:10]

2-element Array{Array,1}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]

#### Copying arrays

Suppose you have an array and want to create another array with similar dimensions, then you can use similar() function as follows

In [45]:
A = collect(1:5);
# Here we have hide the values with the help of semicolon(;)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [46]:
B = similar(A)

5-element Array{Int64,1}:
               0
               1
 139827758481408
               2
               1

In [47]:
A = collect(1:5)

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [48]:
B = similar(A)

5-element Array{Int64,1}:
 139827924468704
 139827918789120
 139827918317216
 139827758481648
 139827815961904

### Matrix Operations

As we know that a two-dimensional (2D) array can be used as a matrix so all the functions that are available for working on arrays can also be used as matrices. The condition is that the dimensions and contents should permit. If you want to type a matrix, use spaces to make rows and semicolon(;) to separate the rows as follows

In [49]:
[2 3 ; 4 5]

2×2 Array{Int64,2}:
 2  3
 4  5

In [50]:
Array[[3,4],[5,6]]

2-element Array{Array,1}:
 [3, 4]
 [5, 6]

In [51]:
[[3,4] [5,6]]

2×2 Array{Int64,2}:
 3  5
 4  6

Accessing the contents of arrays

In Julia, to access the contents/particular element of an array, you need to write the name of the array with the element number in square bracket.

In [52]:
arr = [5,10,15,20,25,30,35,40,45,50]

10-element Array{Int64,1}:
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50

In [53]:
arr[1], arr[2]

(5, 10)

In [54]:
arr[0]

LoadError: BoundsError: attempt to access 10-element Array{Int64,1} at index [0]

In [55]:
arr[end]

50

In [56]:
arr[end-1]

45

In [57]:
# To access more than one element at a time, we can also provide a bunch of index numbers as shown below 
arr[[2,5,6]]

3-element Array{Int64,1}:
 10
 25
 30

In [58]:
arr[[true, false, true, true,true, false, false, true, true, false]]

6-element Array{Int64,1}:
  5
 15
 20
 25
 40
 45

In [59]:
arr2 = [10 11 12; 13 14 15; 16 17 18]

3×3 Array{Int64,2}:
 10  11  12
 13  14  15
 16  17  18

In [60]:
arr2[2]

13

In [61]:
arr2[3]

16

In [62]:
arr2[1,2]

11

In [63]:
arr2[1,3]

12

In [64]:
getindex(arr2,1,2)

11

In [65]:
getindex(arr2,2,3)

15

### Adding Elements

We can add elements to an array in Julia at the end, at the front and at the given index using push!(), pushfirst!() and splice!() functions respectively.
#### At the end

We can use push!() function to add an element at the end of an array. For example,

In [66]:
push!(arr,55)

11-element Array{Int64,1}:
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

Remember we had 10 elements in array arr. Now push!() function added the element 55 at the end of this array.

The exclamation(!) sign represents that the function is going to change the array.

#### At the front

We can use pushfirst!() function to add an element at the front of an array. For example,

In [67]:
pushfirst!(arr,0)

12-element Array{Int64,1}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [68]:
arr

12-element Array{Int64,1}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

#### At a given index

We can use splice!() function to add an element into an array at a given index. For example,

### Removing Elements

We can remove elements at last position, first position and at the given index, from an array in Julia, using pop!(), popfirst!() and splice!() functions respectively.
#### Remove the last element

We can use pop!() function to remove the last element of an array. For example,

In [69]:
pop!(arr)

55

In [70]:
arr

11-element Array{Int64,1}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50

#### Removing the first element

We can use popfirst!() function to remove the first element of an array. For example,

In [71]:
popfirst!(arr)

0

#### Removing element at given position

We can use splice!() function to remove the element from a given position of an array. For example,

In [73]:
splice!(arr,5)

25

### Tuples

Similar to an array, tuple is also an ordered set of elements. Tuples work in almost the same way as arrays but there are following important differences between them −

1. An array is represented by square brackets whereas a tuple is represented by parentheses and commas.
2. Tuples are immutable.

In [1]:
tupl=(5,10,15,20,25,30)

(5, 10, 15, 20, 25, 30)

In [2]:
tupl

(5, 10, 15, 20, 25, 30)

In [3]:
tupl[3:end]

(15, 20, 25, 30)

In [4]:
tupl = ((1,2),(3,4))

((1, 2), (3, 4))

In [5]:
tupl[1]

(1, 2)

In [12]:
tupl[1][2]

2

### Named tuples

A named tuple is simply a combination of a tuple and a dictionary because −
1. A named tuple is ordered and immutable like a tuple and
2. Like a dictionary in named tuple, each element has a unique key which can be used to access it.

#### Keys and values in separate tuples

One way to create named tuples is by providing keys and values in separate tuples.

In [14]:
names_shape = (:corner1, :corner2)

(:corner1, :corner2)

In [15]:
values_shape = ((100, 100), (200, 200))

((100, 100), (200, 200))

In [16]:
shape_item2 = NamedTuple{names_shape}(values_shape)

(corner1 = (100, 100), corner2 = (200, 200))

In [17]:
# accessing the keys
shape_item2.corner1

(100, 100)

In [18]:
shape_item2.corner2

(200, 200)

### Keys and values in a single tuple
We can also create named tuples by providing keys and values in a single tuple.

In [19]:
shape_item = (corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [20]:
shape_item.corner1

(1, 1)

In [21]:
c1, c2, center = shape_item

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [22]:
c1

(1, 1)

### Combining two named tuples
Julia provides us a way to make new named tuples by combining two named tuples together as follows 

In [23]:
colors_shape = (top = "red", bottom = "green")

(top = "red", bottom = "green")

In [24]:
shape_item = (corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [25]:
merge(shape_item, colors_shape)

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0), top = "red", bottom = "green")

#### Named tuples as keyword arguments
If you want to pass a group of keyword arguments to a function, named tuple is a convenient way to do so in Julia. Following is the example of a function that accepts three keyword arguments −

### Numeric Primitive
In any programming language, there are two basic building blocks of arithmetic and computation. They are integers and floating-point values. Built-in representation of the values of integers and floating-point are called numeric primitives. On the other hand, their representation as immediate values in code are called numeric literals.

In [26]:
Sys.WORD_SIZE

64

### Overflow behavior
In Julia, if the maximum representable value of a given type exceeds, then it results in a wraparound behavior. For example

In [27]:
A = typemax(Int64)

9223372036854775807

In [28]:
A+1

-9223372036854775808

It is recommended to explicitly check for wraparound produced by overflow especially where overflow is possible. Otherwise use BigInt type in Arbitrary Precision Arithmetic.

Below is an example of overflow behavior and how we can resolve it −

In [29]:
10^19

-8446744073709551616

In [30]:
big(10)^19

10000000000000000000

### Division errors
Integer division throws a DivideError in the following two exceptional cases −

1. Dividing by zero
2. Dividing the lowest negative number

The rem (remainder) and mod (modulus) functions will throw a DivideError whenever their second argument is zero. The example are given below −

In [31]:
mod(1, 0)

LoadError: DivideError: integer division error

In [32]:
rem(1, 0)

LoadError: DivideError: integer division error

### Floating-point numbers
Another primitive numeric types in Julia is floating-point numbers. It is represented (using E-notation when needed) as follows

In [33]:
2e11

2.0e11

All the above results are Float64. If we would like to enter Float32 literal, they can be written by writing f in the place of e as follows 

In [34]:
0.5f-5

5.0f-6

In [35]:
typeof(ans)

Float32

In [36]:
ans

Float32

In [37]:
bitstring(0.0)

"0000000000000000000000000000000000000000000000000000000000000000"

In [38]:
bitstring(-0.0)

"1000000000000000000000000000000000000000000000000000000000000000"

#### Special floating-point values
The table below represents three specified standard floating-point values. These floating-point values do not correspond to any point on the real number line.

1. inf, -inf, nan

In [39]:
(typemin(Float16),typemax(Float16))

(-Inf16, Inf16)

In [40]:
(typemin(Float32),typemax(Float32))

(-Inf32, Inf32)

In [41]:
(typemin(Float64),typemax(Float64))

(-Inf, Inf)

#### Machine epsilon
Machine epsilon is the distance between two adjacent representable floating-point numbers. It is important to know machine epsilon because most of the real numbers cannot be represented exactly with floating-point numbers.

In Julia, we have eps() function that gives us the distance between 1.0 and the next larger representable floating-point value. The example is given below −

In [42]:
eps(Float32)

1.1920929f-7

In [43]:
eps(Float64)

2.220446049250313e-16

#### Rounding modes
As we know that the number should be rounded to an appropriate representable value if it does not have an exact floating-point representation. Julia uses the default mode called RoundNearest. It rounds to the nearest integer, with ties being rounded to the nearest even integer. For example,

In [44]:
BigFloat("1.510564889",2,RoundNearest)

1.5

### Rational and Complex numbers

#### Rational Numbers
Julia represents exact ratios of integers with the help of rational number type. Let us understand about rational numbers in Julia in further sections −

#### Constructing rational numbers
In Julia REPL, the rational numbers are constructed by using the operator //. Below given is the example for the same 

In [1]:
4//5

4//5

In [2]:
numerator(8//9), denominator(8//9)

(8, 9)

In [3]:
float(2//3)

0.6666666666666666

#### Complex Numbers
As we know that the global constant im, which represents the principal square root of -1, is bound to the complex number. This binding in Julia suffice to provide convenient syntax for complex numbers because Julia allows numeric literals to be contrasted with identifiers as coefficients.

In [4]:
2+3im

2 + 3im

#### Performing Standard arithmetic operations
We can perform all the standard arithmetic operations on complex numbers. The example are given below −

In [5]:
(2 + 3im)*(1 - 2im)

8 - 1im

#### Combining different operands
The promotion mechanism in Julia ensures that combining different kind of operators works fine on complex numbers. Let us understand it with the help of the following example −

#### Functions to manipulate complex values
In Julia, we can also manipulate the values of complex numbers with the help of standard functions.

In [7]:
real(4+7im) #real part of complex number

4

In [8]:
imag(4+7im) #imaginary part of complex number

7

In [9]:
conj(4+7im) # conjugate of complex number

4 - 7im

In [10]:
abs(4+7im) # absolute value of complex number

8.06225774829855

In [11]:
abs2(4+7im) #squared absolute value

65

In [12]:
angle(4+7im) #phase angle in radians

1.0516502125483738

In [13]:
sqrt(7im) #square root of imaginary part

1.8708286933869707 + 1.8708286933869707im

In [14]:
sqrt(4+7im) #square root of complex number

2.455835677350843 + 1.4251767869809258im

In [15]:
cos(4+7im) #cosine of complex number

-358.40393224005317 + 414.96701031076253im

In [16]:
exp(4+7im) #exponential of complex number

41.16166839296141 + 35.87025288661357im

In [17]:
sinh(4+7im) #Hyperbolic sine value of complex number

20.573930095756726 + 17.941143007955223im

### Operators

#### Vectorized “dot” Operators
For each binary operation like ^, there is a corresponding “dot”(.) operation which is used on the entire array, one by one. For instance, if you would try to perform [1, 2, 3] ^ 2, then it is not defined and not possible to square an array. On the other hand, [1, 2, 3] .^ 2 is defined as computing the vectorized result. In the same sense, this vectorized “dot” operator can also be used with other binary operators.

In [18]:
[1, 2, 3].^2

3-element Array{Int64,1}:
 1
 4
 9

#### Chaining Comparisons
In Julia, the comparisons can be arbitrarily chained. In case of numerical code, the chaining comparisons are quite convenient. The && operator for scalar comparisons and & operator for elementwise comparison allows chained comparisons to work fine on arrays.

### Operator precedence
We can also use Base.operator_precedence function to check the numerical precedence of a given operator. The example is given below −

### Basic Mathematical Operator

#### Numerical Conversions
In Julia, the user gets three different forms of numerical conversion. All the three differ in their handling of inexact conversions.

T(x) or convert(T, x) − This notation converts x to a value of T. The result depends upon following two cases −

T is a floating-point type − In this case the result will be the nearest representable value. This value could be positive or negative infinity.

T is an integer type − The result will raise an InexactError if and only if x is not representable by T.

x%T − This notation will convert an integer x to a value of integer type T corresponding to x modulo 2^n. Here n represents the number of bits in T. In simple words, this notation truncates the binary representation to fit.

Rounding functions − This notation takes a type T as an optional argument for calculation. Eg − Round(Int, a) is shorthand for Int(round(a)).

In [19]:
Int8(110)

110

In [20]:
Int8(128)

LoadError: InexactError: trunc(Int8, 128)

In [21]:
Int8(110.0)

110

In [22]:
Int8(3.14)

LoadError: InexactError: Int8(3.14)

In [23]:
110%Int8

110

1. round(x): This function will round x to the nearest integer.	
2. round(T, x): This function will round x to the nearest integer.
3. floor(x): This function will round x towards -Inf returns the nearest integral value of the same type as x. This value will be less than or equal to x.
4. floor(T, x): This function will round x towards -Inf and converts the result to type T. It will throw an InexactError if the value is not representable.	
5. floor(T, x): This function will round x towards -Inf and converts the result to type T. It will throw an InexactError if the value is not representable.
6. ceil(x): This function will round x towards +Inf and returns the nearest integral value of the same type as x. This value will be greater than or equal to x.
7. ceil(T, x): This function will round x towards +Inf and converts the result to type T. It will throw an InexactError if the value is not representable.
8. trunc(x): This function will round x towards zero and returns the nearest integral value of the same type as x. The absolute value will be less than or equal to x.	
9. trunc(T, x): This function will round x towards zero and converts the result to type T. It will throw an InexactError if the value is not representable.

In [1]:
round(3.8)

4.0

In [2]:
round(Int, 3.8)

4

### Division functions

1. div(x,y), x÷y: It is the quotation from Euclidean division. Also called truncated division. It computes x/y and the quotient will be rounded towards zero.
2. fld(x,y): It is the floored division. The quotient will be rounded towards -Inf i.e. largest integer less than or equal to x/y. It is shorthand for div(x, y, RoundDown).
3. cld(x,y): It is ceiling division. The quotient will be rounded towards +Inf i.e. smallest integer less than or equal to x/y. It is shorthand for div(x, y, RoundUp).
4. rem(x,y): remainder; satisfies x == div(x,y)*y + rem(x,y); sign matches x
5. mod(x,y): It is modulus after flooring division. This function satisfies the equation x == fld(x,y)*y + mod(x,y). The sign matches y.
6. mod1(x,y): This is same as mod with offset 1. It returns r∈(0,y] for y>0 or r∈\[y,0) for y<0, where mod(r, y) == mod(x, y).
7. mod2pi(x): It is modulus with respect to 2pi. It satisfies 0 <= mod2pi(x) < 2pi
8. divrem(x,y): It is the quotient and remainder from Euclidean division. It equivalents to (div(x,y),rem(x,y)).
9. fldmod(x,y): It is the floored quotation and modulus after division. It is equivalent to (fld(x,y),mod(x,y))
10. gcd(x,y...): It is the greatest positive common divisor of x, y,...
11. lcm(x,y...): It represents the least positive common multiple of x, y,...

### Sign and Absolute value functions

1. abs(x): It the absolute value of x. It returns a positive value with the magnitude of x.
2. abs2(x): It returns the squared absolute value of x.
3. sign(x): This function indicates the sign of x. It will return -1, 0, or +1.
4. signbit(x): This function indicates whether the sign bit is on (true) or off (false). In simple words, it will return true if the value of the sign of x is -ve, otherwise it will return false.
5. copysign(x,y): It returns a value Z which has the magnitude of x and the same sign as y.
6. flipsign(x,y): It returns a value with the magnitude of x and the sign of x*y. The sign will be flipped if y is negative. Example: abs(x) = flipsign(x,x).

### Power, Logs, and Roots

1. sqrt(x), √x: It will return the square root of x. For negative real arguments, it will throw DomainError.
2. cbrt(x), ∛x: It will return the cube root of x. It also accepts the negative values.
3. hypot(x,y): It will compute the hypotenuse √|𝑥|2+|𝑦|2of right-angled triangle with other sides of length x and y. It is an implementation of an improved algorithm for hypot(a,b) by Carlos and F.Borges.
4. exp(x): It will compute the natural base exponential of x i.e. 𝑒𝑥
5. expm1(x): It will accurately compute 𝑒𝑥−1 for x near zero.
6. ldexp(x,n): It will compute 𝑋 ∗ 2𝑛 efficiently for integer values of n.
7. log(x): It will compute the natural logarithm of x. For negative real arguments, it will throw DomainError.
8. log(b,x): It will compute the base b logarithm of x. For negative real arguments, it will throw DomainError.
9. log2(x): It will compute the base 2 logarithm of x. For negative real arguments, it will throw DomainError.
10. log10(x): It will compute the base 10 logarithm of x. For negative real arguments, it will throw DomainError.
11. log1p(x): It will accurately compute the log(1+x) for x near zero. For negative real arguments, it will throw DomainError.
12. exponent(x): It will calculate the binary exponent of x.
13. significand(x): It will extract the binary significand (a.k.a. mantissa) of a floating-point number x in binary representation. If x = non-zero finite number, it will return a number of the same type on the interval \[1,2), else x will be returned.

### String

A string may be defined as a finite sequence of one or more characters. They are usually enclosed in double quotes. 

1. Strings are immutable, i.e., we cannot change them once they are created.
2. It needs utmost care while using two specific characters − double quotes(“), and dollar sign\($). It is because if we want to include a double quote character in the string then it must precede with a backslash; otherwise we will get different results because then the rest of the string would be interpreted as Julia code. On the other hand, if we want to include a dollar sign then it must also precede with a backslash because dollar sign is used in string interpolation./p>
3. In Julia, the built-in concrete type used for strings as well as string literals is String which supports full range of Unicode characters via the UTF-8 encoding.
4. All the string types in Julia are subtypes of the abstract type AbstractString. If you want Julia to accept any string type, you need to declare the type as AbstractString.
5. Julia has a first-class type for representing single character. It is called AbstractChar.

In [1]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [2]:
typeof(ans)

Char

In [5]:
Char(97)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [6]:
# With Char values, we can do some arithmetic as well as comparisons.
'X' < 'x'

true

In [7]:
'X' <= 'x' <= 'Y'

false

In [8]:
'X' <= 'a' <= 'Y'

false

In [9]:
'x' - 'b'

22

In [11]:
'z' - 1

'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)

#### Delimited by double quotes or triple double quotes
As we discussed, strings in Julia can be declared using double or triple double quotes. For example, if you need to add quotations to a part in a string, you can do so using double and triple double quotes as shown below −

In [12]:
str = "This is Julia Programming Language.\n"

"This is Julia Programming Language.\n"

In [13]:
"""See the "quote" characters"""

"See the \"quote\" characters"

#### Performing arithmetic and other operations with end
Just like a normal value, we can perform arithmetic as well as other operations with end. Check the below given example −

In [14]:
str[end-1]

'.': ASCII/Unicode U+002E (category Po: Punctuation, other)

#### Extracting substring by using range indexing
We can extract substring from a string by using range indexing. Check the below given example −

In [15]:
str[6:9]

"is J"

#### Using SubString
In the above method, the Range indexing makes a copy of selected part of the original string, but we can use SubString to create a view into a string as given in the below example −

In [16]:
substr = SubString(str, 1, 4)

"This"

#### Unicode and UTF-8
Unicode characters and strings are fully supported by Julia programming language. In character literals, Unicode \u and \U escape sequences as well as all the standard C escape sequences can be used to represent Unicode code points. It is shown in the given example −

In [17]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

#### String Concatenation
Concatenation is one of the most useful string operations. Following is an example of concatenation −

In [18]:
A = "Hello"
B = "Julia Programming Language"
string(A, ", ", B, ".\n")

"Hello, Julia Programming Language.\n"

#### Interpolation
It is bit cumbersome to concatenate strings using concatenation. Therefore, Julia allows interpolation into strings and reduce the need for these verbose calls to strings. This interpolation can be done by using dollar sign ($). For example −

In [19]:
"$A, $B.\n"

"Hello, Julia Programming Language.\n"

In [20]:
"100 + 10 = $(100 + 10)"

"100 + 10 = 110"

In [21]:
str = """
                  This is,
                  Julia Programming Language.
               """


"   This is,\n   Julia Programming Language.\n"

In [22]:
"abababab" < "Tutorialspoint"

false

#### Search operators
Julia provides us findfirst and findlast functions to search for the index of a particular character in string. You can check the below example of both these functions −

In [23]:
findfirst(isequal('o'), "Tutorialspoint")

4

In [25]:
findnext(isequal('o'), "Tutorialspoint", 1)

4

In [27]:
findnext(isequal('o'), "Tutorialspoint", 5)

11

In [28]:
occursin("Julia", "This is, Julia Programming.")

true

#### The repeat() and join() functions
In the perspective of Strings in Julia, repeat and join are two useful functions. Example below explains their use −

In [29]:
repeat("Tutorialspoint.com ", 5)

"Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com "

In [30]:
join(["TutorialsPoint","com"], " . ")

"TutorialsPoint . com"

### Non-standard String Literals
Literal is a character or a set of characters which is used to store a variable.

#### Raw String Literals
Raw String literals are another useful non-standard string literal. They, without interpolation or unescaping can be expressed in the form of raw”…”. They create ordinary String objects containing enclosed contents same as entered without interpolation or unescaping.

In [31]:
println(raw"\\ \\\"")

\\ \"


#### Byte Array Literals
Byte array literals is one of the most useful non-standard string literals. It has the following rules −
1. ASCII characters as well as escapes will produce a single byte.
2. Octal escape sequence as well as \x will produce the byte corresponding to the escape value.
3. The Unicode escape sequence will produce a sequence of bytes encoding.

In [32]:
b"DATA\xff\u2200"

8-element Base.CodeUnits{UInt8,String}:
 0x44
 0x41
 0x54
 0x41
 0xff
 0xe2
 0x88
 0x80

In [33]:
# The above resulting byte array is not a valid UTF-8 string as you can see below −
isvalid("DATA\xff\u2200")

false

#### Version Number Literals
Version Number literals are another useful non-standard string literal. They can be the form of v”…”. VNL create objects namely VersionNumber. These objects follow the specifications of semantic versioning.

#### Regular Expressions
Julia has Perl-compatible Regular Expressions, which are related to strings in the following ways −
1. RE are used to find regular patterns in strings.
2. RE are themselves input as strings. It is parsed into a state machine which can then be used efficiently to search patterns in strings.

In [34]:
r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [35]:
typeof(ans)

Regex

We can use occursin as follows to check if a regex matches a string or not −

In [36]:
occursin(r"^\s*(?:#|$)", "not a comment")

false

In [37]:
occursin(r"^\s*(?:#|$)", "# a comment")

true